baseURL = 'https://tinytapeout.com'
languageCode = 'en-us'
title = 'Tiny Tapeout'
theme = "learn"


[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^CF_']

[[menu.shortcuts]]
  name = "<i class='fa fa-shopping-basket'></i> Store"
  url = "https://store.tinytapeout.com/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  Description = "Quicker, easier and cheaper than ever to make your own chip!"
  themeVariant = "tinytapeout"
  defaultContentLanguage = 'en'
  disableLightbox = true
  workshopFeedbackLink = "https://docs.google.com/forms/d/e/1FAIpQLSfQ7-CfwX139EeZ_mK5B7B-zrs1COUbZEk0LXseT43QYZMCIA/viewform?usp=header"
  

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
  [Languages.en]
    title = "Quicker, easier and cheaper to make your own chip!"
    weight = 1
    languageName = "English"

  [Languages.es]
    title = "¡Hacer tu propio chip de forma más rápida, más fácil y más barata!"
    weight = 2
    languageName = "Español"

  [Languages.ua]
    title = "Документація українською"
    weight = 3
    languageName = "Українська"

  [Languages.it]
    title = "Crea il tuo microchip in modo più veloce, più semplice ed economico!"
    weight = 4
    languageName = "Italiano"

#disableLanguages = ['es', 'it']
